trigger:
  - main

variables:
  - group: dbw-cicd-cnsibm-dev
  - group: dbw-cicd-cnsibm-prd

   
  - name: vmImageName
    value: 'windows-latest'
  - name: notebooksPath
    value: "CNS_IBM"

pool: 
  # vmImage: $(vmImageName)
  name: 'AAP'
  demands: 'Agent.OS -equals Linux'


stages:
  - template: templates/deploy-notebooks.yml
    parameters:
      stageId: "Deploy_to_Dev_Environment"
      env: "dev"
      environmentName: $(dev-envivonment-name)
      resourceGroupName: $(dev-resource-group-name)
      serviceConnection: $(dev-service-connection-name)
      notebooksPath: $(notebooksPath)
  
  - template: templates/deploy-notebooks.yml
    parameters:
      dependsOn: ["Deploy_to_Dev_Environment"]
      stageId: "Deploy_to_Prd_Environment"
      env: "prd"
      environmentName: $(prd-envivonment-name)
      resourceGroupName: $(prd-resource-group-name)
      serviceConnection: $(prd-service-connection-name)
      notebooksPath: $(notebooksPath)

 
